version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAGitProject
  gitUsername: siqagituser
  gitBranch: main
